[package]
name = "my-postgres-core"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
with-tls = ["postgres-openssl", "openssl"]
with-logs-and-telemetry = ["my-telemetry"]

[dependencies]
my-json = { tag = "0.2.0", git = "https://github.com/MyJetTools/my-json.git" }
rust-extensions = { tag = "0.1.3", git = "https://github.com/MyJetTools/rust-extensions.git", features = [
    "objects-pool",
] }
my-telemetry = { tag = "1.0.1", optional = true, git = "https://github.com/MyJetTools/my-telemetry.git" }

tokio = { version = "*", features = ["full"] }
tokio-postgres = { version = "*", features = ["with-chrono-0_4"] }
serde = { version = "*", features = ["derive"] }
async-trait = "*"
serde_json = "*"
lazy_static = "*"

#tls
postgres-openssl = { version = "*", optional = true }
openssl = { version = "*", optional = true }
