name: Test it

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build default
        run: cargo build

      - name: Build with-tls          
        run: cargo build --features with-tls

      - name: Build with-telemetry          
        run: cargo build --features with-logs-and-telemetry      

      - name: Build failed-sql-to-console          
        run: cargo build --features failed-sql-to-console           